RIDE
====
How to Install this fork
====

I only did this on linux, ubuntu 14.04
having installed latest Ride release, clone this repo and replace /usr/local/lib/python2.7/dist-packages/robotide with
src/robotide from this cloned repo.

